# Path to your oh-my-zsh installation.
ZSH=/usr/share/oh-my-zsh/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bullet-train"

# Theme settings
BULLETTRAIN_GIT_BG="green"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias git-branch-cleanup='git branch --merged | grep -v "\*" | grep -v master | grep -v dev | xargs -n 1 git branch -d'
alias frontdoor-socks-tunnel='nohup ssh -D 8123 -f -C -q -N frontdoor > /tmp/nohup.out &'

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras vagrant colorize colored-man sudo screen docker symfony2)

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /etc/profile.d/vte.sh
#source /usr/share/doc/pkgfile/command-not-found.zsh

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$HOME/.composer/vendor/bin:$HOME/.gem/bin:$HOME/.hem/gems/ruby/2.2.0/bin:/opt/hem/bin:/opt/hem/embedded/bin:$PATH
export MANPATH="/usr/local/man:$MANPATH"
export TERM="xterm-256color"

# Load environment variables containing private data
source ~/.zshenv

# Number of processor cores for node-gyp addon build tool
export npm_config_jobs=9

# Vagrant VM settings
export VAGRANT_VM_CPUS=2
export VAGRANT_VM_MEMORY=4096

# command autocompletions
fpath=(/usr/share/licenses/zsh-completions $fpath)

export EDITOR='vim'

# History related settings
HISTSIZE=1200                   # lines of history to maintain memory
setopt EXTENDED_HISTORY         # save timestamp and runtime information
setopt APPEND_HISTORY           # append rather than overwrite history file
setopt HIST_EXPIRE_DUPS_FIRST   # allow dups, but expire old ones when I hit HISTSIZE

alsi
